//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinthe {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class LootConstantes : global::System.Configuration.ApplicationSettingsBase {
        
        private static LootConstantes defaultInstance = ((LootConstantes)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LootConstantes())));
        
        public static LootConstantes Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SortCarteForce {
            get {
                return ((int)(this["SortCarteForce"]));
            }
            set {
                this["SortCarteForce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SortCarteVitesse {
            get {
                return ((int)(this["SortCarteVitesse"]));
            }
            set {
                this["SortCarteVitesse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SortCarteVision {
            get {
                return ((int)(this["SortCarteVision"]));
            }
            set {
                this["SortCarteVision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SortPotionVision {
            get {
                return ((int)(this["SortPotionVision"]));
            }
            set {
                this["SortPotionVision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SortPotionForce {
            get {
                return ((int)(this["SortPotionForce"]));
            }
            set {
                this["SortPotionForce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SortPotionVitesse {
            get {
                return ((int)(this["SortPotionVitesse"]));
            }
            set {
                this["SortPotionVitesse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SortVitesse {
            get {
                return ((int)(this["SortVitesse"]));
            }
            set {
                this["SortVitesse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SortVision {
            get {
                return ((int)(this["SortVision"]));
            }
            set {
                this["SortVision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SortForce {
            get {
                return ((int)(this["SortForce"]));
            }
            set {
                this["SortForce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ClesOuvrePorte {
            get {
                return ((int)(this["ClesOuvrePorte"]));
            }
            set {
                this["ClesOuvrePorte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ForceDragon {
            get {
                return ((int)(this["ForceDragon"]));
            }
            set {
                this["ForceDragon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ForceGobelin {
            get {
                return ((int)(this["ForceGobelin"]));
            }
            set {
                this["ForceGobelin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ForceSpectre {
            get {
                return ((int)(this["ForceSpectre"]));
            }
            set {
                this["ForceSpectre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0")]
        public global::System.Windows.Point SortCarteTeleportation {
            get {
                return ((global::System.Windows.Point)(this["SortCarteTeleportation"]));
            }
            set {
                this["SortCarteTeleportation"] = value;
            }
        }
    }
}
