//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinthe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class QuantiteLoot : global::System.Configuration.ApplicationSettingsBase {
        
        private static QuantiteLoot defaultInstance = ((QuantiteLoot)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new QuantiteLoot())));
        
        public static QuantiteLoot Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int nbCartes {
            get {
                return ((int)(this["nbCartes"]));
            }
            set {
                this["nbCartes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int nbClés {
            get {
                return ((int)(this["nbClés"]));
            }
            set {
                this["nbClés"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int nbPilulesVision {
            get {
                return ((int)(this["nbPilulesVision"]));
            }
            set {
                this["nbPilulesVision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int nbPilulesForce {
            get {
                return ((int)(this["nbPilulesForce"]));
            }
            set {
                this["nbPilulesForce"] = value;
            }
        }
    }
}
